### ISSUE TITLE
Mention in README that many openjdk packages on Linux doesn't include JavaFX

### ISSUE THREAD

**Issue by rexim** [ForNeVeR/checktimer#31]
I tried to build the project on my NixOS machine and faced this problem https://github.com/scalafx/scalafx/issues/141 It would be good to have it mentioned in the README.

@ForNeVeR I can resolve this issue in a couple of days if you don't have time on that.

**Comment by ForNeVeR** [comment]
See also https://github.com/NixOS/nixpkgs/issues/16727

**Comment by ForNeVeR** [comment]
Well, is there a way for us to include JavaFX from maven?

**Comment by ForNeVeR** [comment]
Ah, god, it's so problematic: http://stackoverflow.com/a/15283999/2684760

**Comment by ForNeVeR** [comment]
Closing as obsolete: we no longer rely on JavaFX embedded in JDK.
